### ISSUE TITLE
Missing VboxIdPath file stops package verification

### ISSUE THREAD

**Issue by pauby** [chocolatey/package-verifier#96]
Since Package Verifier 0.4.0-51 the `VboxIdPath` key has been required in the `package-verifier.exe.config` file. If the file does not exist, Package Verifier will complain and will not verify the package:

```
2020-08-28 13:59:01,808 7 [INFO ] - ========== MarkdownMonster.Portable v1.23.18.3 ==========
2020-08-28 13:59:01,808 7 [INFO ] - Testing Package: MarkdownMonster.Portable Version: 1.23.18.3
2020-08-28 13:59:01,808 7 [WARN ] - chocolatey-package-verifier had an error on SERVER (with user USER):
System.IO.FileNotFoundException: Could not find file 'C:\tools\chocolatey-package-verifier\.vagrant\machines\default\virtualbox\id'.
File name: 'C:\tools\chocolatey-package-verifier\.vagrant\machines\default\virtualbox\id'
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at chocolatey.package.verifier.infrastructure.filesystem.DotNetFileSystem.get_file_encoding(String filePath)
   at chocolatey.package.verifier.infrastructure.filesystem.DotNetFileSystem.read_file(String filePath)
   at chocolatey.package.verifier.infrastructure.app.tasks.TestPackageTask.test_package(VerifyPackageMessage message)
```

My understanding would be that the file in `VboxIdPath` should exist if Package Verifier has created a Vagrant VM, sandboxed it and is using it. It should _not_ exist if that VB has not been created and in that case, instead of stopping verification, should go on and create the VM, snapshot it etc.

Today there were other unrelated issues with Verifier so as a belt and braces the Vagrant VM was removed. This is how the issue was spotted as Verifier would no longer verify packages.

The solution to the problem has been to roll Package Verifier back to 0.4.0-38 which doesn't have the `VboxIdPath` key in the `package-verifier.exe.config` file. Given the changes that have been made to Package Scanner and Verifier, with a new 'flow' for packages going through moderation, this isn't ideal. But it is the only solution that worked.

**Comment by ferventcoder** [comment]
This looks like it might have been caused by #77. https://github.com/chocolatey/package-verifier/commit/243bc7c19b000b8175aea58d0e7b029f9260ea9a#diff-943f03b4181625724f13ae8ef798df44R76
